### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ts-eng** [karpathy/llama2.c#140]
$ torchrun --nproc_per_node 1 export_meta_llama_bin.py
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "export_meta_llama_bin.py", line 85, in <module>
    generator = Llama.build(
  File "/home/tseng/workspace/project/llama/llama/generation.py", line 96, in build
    model = Transformer(model_args)
  File "/home/tseng/workspace/project/llama/llama/model.py", line 259, in __init__
    self.layers.append(TransformerBlock(layer_id, params))
  File "/home/tseng/workspace/project/llama/llama/model.py", line 221, in __init__
    self.attention = Attention(args)
  File "/home/tseng/workspace/project/llama/llama/model.py", line 136, in __init__
    self.cache_v = torch.zeros(
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 5.93 GiB total capacity; 5.23 GiB already allocated; 17.00 MiB free; 5.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 5031) of binary: /home/tseng/miniconda3/envs/open-mmlab/bin/python
Traceback (most recent call last):
  File "/home/tseng/miniconda3/envs/open-mmlab/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
  File "/home/tseng/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/tseng/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/tseng/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/tseng/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tseng/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
export_meta_llama_bin.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-27_21:36:51
  host      : tseng-TUF-GAMING-FX504GM-FX80GM
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5031)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**How to solve this problem?**

**Comment by tairov** [comment]
Hi @ts-eng , please share hardware & os specs on you system

**Comment by ts-eng** [comment]
> Hi @ts-eng , please share hardware & os specs on you system

CPU: Intel Core i5-8300H(2.3GHz/L3 8M), 16GB memory
GPU: NVIDIA GeForce GTX 1060, 6GB memory
OS: Ubuntu 20.04
