### ISSUE TITLE
The front operation is still good, and nothing has changed, and an error is reported，How to solve it

### ISSUE THREAD

**Issue by musellama** [karpathy/llama2.c#144]
Traceback (most recent call last):
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2822, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2515, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1715, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1328, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 571, in compile_to_module
    code = self.codegen()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 522, in codegen
    self.scheduler.codegen()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/scheduler.py", line 1167, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/codegen/triton.py", line 1495, in codegen_nodes
    return self.codegen_node_schedule(node_schedule, numel, rnumel)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/codegen/triton.py", line 1551, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/codegen/triton.py", line 1216, in codegen_kernel
    "signature": dict(enumerate(map(signature_of, signature))),
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_inductor/codegen/triton.py", line 48, in signature_of
    tye = JITFunction._type_of(arg.dtype)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/triton/runtime/jit.py", line 166, in _type_of
    ty = {
KeyError: torch.complex64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maguoheng/llama2.c/train.py", line 251, in <module>
    losses = estimate_loss()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/maguoheng/llama2.c/train.py", line 211, in estimate_loss
    logits, loss = model(X, Y)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/llama2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised KeyError: torch.complex64

Set torch._dynamo.config.verbose=True for more information

You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

The environment is win11, WSL2, python==3.9

**Comment by musellama** [comment]
Please help me

**Comment by karpathy** [comment]
use --compile=False

**Comment by musellama** [comment]
Sorry, but I can go into more detail about which script to change

**Comment by musellama** [comment]
python -m train.py --compile=False --eval_iters=1 --batch_size=1

**Comment by musellama** [comment]
There is this error

   return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by musellama** [comment]
> use --compile=False
python -m train.py --compile=False --eval_iters=1 --batch_size=1

There is this error

return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)

**Comment by couldn** [comment]
same question

**Comment by chengshenlian** [comment]
It is likely due to insufficient GPU memory. My configuration is as follows:
Operating System: Ubuntu 20.04
CPU: Intel Core i5 9600K
GPU: NVIDIA RTX 3080 with 10GB VRAM

Initially, I encountered the same error. However, I managed to resolve it by taking the following steps:

I reduced the size of the dataset in the 'data' directory.
I used the command 'python -m train.py --compile=False --eval_iters=1 --batch_size=1' to decrease the batch size.
Both of these methods allowed me to successfully run 'train.py'.

Please note that the error may have been caused by running out of GPU memory due to the large dataset or batch size. By reducing them, I was able to avoid this issue and complete the training process successfully.

**Comment by musellama** [comment]
> 这可能是由于 GPU 内存不足。我的配置如下： 操作系统： Ubuntu 20.04 CPU： 英特尔酷睿 i5 9600K GPU ： 英伟达 RTX 3080 与 10GB 显存
> 
> 最初，我遇到了同样的错误。但是，我设法通过以下步骤解决了它：
> 
> 我减小了“data”目录中数据集的大小。我使用命令'python -m train.py --compile=False --eval_iters=1 --batch_size=1'来减小批处理大小。这两种方法都使我能够成功地运行“train.py”。
> 
> 请注意，该错误可能是由于数据集或批量大小过大而导致 GPU 内存不足引起的。通过减少它们，我能够避免这个问题并成功完成培训过程。

Mine is a graphics card of the NVIDIA 4090 24G

**Comment by musellama** [comment]
> same question

My CUDA version is 12.0, can you tell me your CUDA version

**Comment by musellama** [comment]
> 同样的问题

@musellama  问题解决了嘛 你的 cuda 版本 是啥啊 还有 torch python  啥的，我刚开始还好好的，突然就不行了
