### ISSUE TITLE
13B doesn't work for unknown reasons

### ISSUE THREAD

**Issue by skeetmtp** [karpathy/llama2.c#164]
Hello, 

Even if it's low priority, I created this issue to follow investigations.
Feel free to close it, if it's not the way to go.

**Comment by skeetmtp** [comment]
I gave asan a first try
```
rundebug: run.c 
	$(CC) -O1 -g -o run run.c -lm -fsanitize=address -fno-omit-frame-pointer
```

I need to investigate more, but here first result:
```
lempire@spark-lab0:~/alban/llama2.c$ ./run /home/lempire/alban/llama/llama2_13b.bin 1.0 20 "// js function to remove all fields named 'id' from given object\n"
<s>
=================================================================
==76171==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f14e6469800 at pc 0x556834c5c48a bp 0x7ffedf1e5310 sp 0x7ffedf1e5300
READ of size 4 at 0x7f14e6469800 thread T0
    #0 0x556834c5c489 in matmul /home/lempire/alban/llama2.c/run.c:202
    #1 0x556834c5d525 in transformer /home/lempire/alban/llama2.c/run.c:337
    #2 0x556834c5e9da in main /home/lempire/alban/llama2.c/run.c:550
    #3 0x7f2108d7e082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
    #4 0x556834c5b56d in _start (/home/lempire/alban/llama2.c/run+0x256d)

0x7f14e6469800 is located 0 bytes to the right of 1677721600-byte region [0x7f1482469800,0x7f14e6469800)
allocated by thread T0 here:
    #0 0x7f21091a8a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x556834c5b93d in malloc_run_state /home/lempire/alban/llama2.c/run.c:89
    #2 0x556834c5e7b6 in main /home/lempire/alban/llama2.c/run.c:531
    #3 0x7f2108d7e082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/lempire/alban/llama2.c/run.c:202 in matmul
Shadow bytes around the buggy address:
  0x0fe31cc852b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe31cc852c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe31cc852d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe31cc852e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe31cc852f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe31cc85300:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe31cc85310: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe31cc85320: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe31cc85330: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe31cc85340: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe31cc85350: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==76171==ABORTING
```

It seems matmul is touching the memory just after the block allocated by
```
s->key_cache = calloc(p->n_layers * p->seq_len * p->dim, sizeof(float));
```

**Comment by kroggen** [comment]
Hello! Could you check if the changes of #154 fix the problem?

**Comment by skeetmtp** [comment]
Hello, 

No more issue with you patch!
Based on your commit I switched to ubsan as it is more appropriate to catch this kind of bug
```
rundebug: run.c 
	$(CC) -O1 -g -o run run.c -lm -fsanitize=undefined -fno-omit-frame-pointer
```
And bingo !
Run against karpathy/master:

```
run.c:135:33: runtime error: signed integer overflow: 204800 * 13824 cannot be represented in type 'int'
run.c:137:40: runtime error: signed integer overflow: 552960 * 5120 cannot be represented in type 'int'
run.c:139:33: runtime error: signed integer overflow: 204800 * 13824 cannot be represented in type 'int'
<s>
run.c:313:43: runtime error: signed integer overflow: 13824 * 158720 cannot be represented in type 'int'
```

**Comment by skeetmtp** [comment]
Still got error with ubsan on your fork though :/ 
```
lempire@spark-lab0:~/alban/fork/llama2.c$ ./run /home/lempire/alban/llama/llama2_13b.bin 1.0 20 "// js function to remove all fields named 'id' from given object\n"
run.c:132:33: runtime error: signed integer overflow: 204800 * 13824 cannot be represented in type 'int'
run.c:134:40: runtime error: signed integer overflow: 552960 * 5120 cannot be represented in type 'int'
run.c:136:33: runtime error: signed integer overflow: 204800 * 13824 cannot be represented in type 'int'
```

**Comment by skeetmtp** [comment]
No more error nor from ubsan nor asan with #154 !!

**Comment by kroggen** [comment]
Cool! Thank you! =)

**Comment by ozabluda** [comment]
https://github.com/karpathy/llama2.c/pull/154 is a much better fix IMHO

**Comment by karpathy** [comment]
closing as this PR fixed the issue, ty all https://github.com/karpathy/llama2.c/pull/367
