### ISSUE TITLE
bug: export of Meta LLaMA 2 chat models fails

### ISSUE THREAD

**Issue by nikolaydubina** [karpathy/llama2.c#192]
## steps to reproduce

1. get llama 2 official models
2. run `python3 export_meta_llama_bin.py <llama-2-7b-chat folder> llama2_7b_chat.bi`

get error

```bash
Traceback (most recent call last):
  File "/Users/nikolaydubina/Workspace/llama2.c/export_meta_llama_bin.py", line 112, in <module>
    load_and_export(model_path, output_path)
  File "/Users/nikolaydubina/Workspace/llama2.c/export_meta_llama_bin.py", line 95, in load_and_export
    params = json.load(f)
             ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by RahulSChand** [comment]
Can you check if you have `params.json` file inside your `<llama-2-7b-chat folder>` ? And open it using vim or any editor to see if it has valid data?

**Comment by nikolaydubina** [comment]
@RahulSChand, you are right. I got corrupted chat models. will re-download and try again. likely will close this ticket. just need to confirm it is working first.

**Comment by nikolaydubina** [comment]
ok, all good. it was my broken llama model weights.
