### ISSUE TITLE
i wanna run python train.py but get errors

### ISSUE THREAD

**Issue by doublegsoft** [karpathy/llama2.c#273]
Ran python train.py on mac, and get errors below, and how can i solve it?

Traceback (most recent call last):
  File "/Volumes/EXPORT/local/opens/llama2.c/train.py", line 257, in <module>
    losses = estimate_loss()
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Volumes/EXPORT/local/opens/llama2.c/train.py", line 217, in estimate_loss
    logits, loss = model(X, Y)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/Users/christian/anaconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised KeyError: torch.complex64

**Comment by RahulSChand** [comment]
can you try changing the line 71 in `train.py` and set `compile=False`?

**Comment by karpathy** [comment]
Also try `git pull` i think you are using an old version of the code

**Comment by edisondeng** [comment]
What will be the proper hardware to run this train.py ?  It seems it is very slow on my i7-12000H + RTX3070 
tks

**Comment by edisondeng** [comment]
What will be the proper hardware to run this train.py ? It seems it is very slow on my i7-12700H + RTX3060
tks

**Comment by sahyagiri** [comment]
> torch.complex64

torch.complex64 won't work in MAC. You need to disable cuda and use torch cpu with mac
