### ISSUE TITLE
Fail to train with compile as true.

### ISSUE THREAD

**Issue by dongwangdw** [karpathy/llama2.c#53]
I just want to try the train.py. Then I ran this command:
` python -m train.py --compile=False --eval_iters=10 --batch_size=8` although I got two GPU. But I did not find a way to use them all.

This works well but it would loop over around 2.0. The loss would not reduce any longer.

And when I set --compile= True. It would crash.
The traceback does not include any valuble info but this line: `KeyError: torch.complex64`.

I searched this error it says the support of complex64. I can not keep going here.
Please help. Thanks.

**Comment by naed90** [comment]
+1

Currently looking into this too. Posting the stack trace here in case someone else encounters this too.

Stack trace:
```
Traceback (most recent call last):
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2822, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2515, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1715, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1328, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/graph.py", line 571, in compile_to_module
    code = self.codegen()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/graph.py", line 522, in codegen
    self.scheduler.codegen()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/scheduler.py", line 1167, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/codegen/triton.py", line 1495, in codegen_nodes
    return self.codegen_node_schedule(node_schedule, numel, rnumel)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/codegen/triton.py", line 1551, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/codegen/triton.py", line 1216, in codegen_kernel
    "signature": dict(enumerate(map(signature_of, signature))),
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_inductor/codegen/triton.py", line 48, in signature_of
    tye = JITFunction._type_of(arg.dtype)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/triton/runtime/jit.py", line 166, in _type_of
    ty = {
KeyError: torch.complex64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 258, in <module>
    losses = estimate_loss()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "train.py", line 214, in estimate_loss
    logits, loss = model(X, Y)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/anaconda/envs/llama_2_karpathy/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised KeyError: torch.complex64
```

**Comment by marco-ve** [comment]
Having the same issue, same stack trace as far as I can see. Tried updating triton via pip after reading the suggestion here, but no luck with triton 2.0.0.post1.

**Comment by karpathy** [comment]
(fwiw I currently train with --compile=False. Works fine just a bit slower.)

**Comment by naed90** [comment]
Currently seems 

> Having the same issue, same stack trace as far as I can see. Tried updating triton via pip after reading the suggestion here, but no luck with triton 2.0.0.post1.

Yeah, also with the nightly version of triton it doesn't work. I took a look again, and seems that triton just doesn't support compiling with complex64. Probably either a triton or a pytorch bug. I wonder how this works elsewhere.

**Comment by dongwangdw** [comment]
> (fwiw I currently train with --compile=False. Works fine just a bit slower.)

yes, but I want to compile the model. So I enabled compile.
I wonder how you compile the model? Any special config. My GPU is Tesla V100.

**Comment by awgu** [comment]
Have you guys tried running with a nightly version of PyTorch? Maybe there was a change to how TorchInductor handles complex floats.

FWIW, when I last ran on Monday morning with both single-GPU and multi-GPU (DDP), I was able to run with `torch.compile()`. I build `torch` from source and use `triton` 2.0.0.

**Comment by dongwangdw** [comment]
> Have you guys tried running with a nightly version of PyTorch? Maybe there was a change to how TorchInductor handles complex floats.
> 
> FWIW, when I last ran on Monday morning with both single-GPU and multi-GPU (DDP), I was able to run with `torch.compile()`. I build `torch` from source and use `triton` 2.0.0.

pytorch does support complex64.
```
import torch

a = torch.tensor([1.0, 2.0], dtype=torch.double)
b = a.type(torch.complex64)
```
I installed the lateset triton and got a new error:

```
from triton import next_power_of_2
ImportError: cannot import name 'next_power_of_2' from 'triton' (unknown location)
```

**Comment by tcapelle** [comment]
so much on the table by no using compile...

**Comment by dongwangdw** [comment]
I found some clue it is the function precompute_freqs_cis which uses torch.polar to convert tensors to complex64.
But triton does not support this. see [here](https://github.com/openai/triton/blob/main/python/triton/runtime/jit.py#L215C11-L215C11). 
This is interesting. The simple way is to replace this function without using complex type from my point.
But I may miss some background knowledge here.
@tcapelle what is you point?

**Comment by dongwangdw** [comment]
#103 this may fix this issue.

**Comment by jataylo** [comment]
@dongwangdw This appears to work using tip-of-tree of pytorch. It will provide a fallback for the complex ops and output a warning

`/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/lowering.py:1298: UserWarning: Torchinductor does not support code generation for complex operators. Performance may be worse than eager.`

**Comment by dongwangdw** [comment]
Close this due to the fix merged and I have verified it works.
